In [1]:
%pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\Users\snehal\AppData\Local\Programs\Python\Python314\Lib\site-packages (1.9.1)
Requirement already satisfied: numpy>=1.24.1 in c:\Users\snehal\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (2.5.2)
Requirement already satisfied: scipy>=1.10.0 in c:\Users\snehal\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (1.18.1)
Requirement already satisfied: joblib>=1.4.0 in c:\Users\snehal\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (1.6.0)
Requirement already satisfied: narwhals>=2.0.1 in c:\Users\snehal\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (2.26.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\Users\snehal\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (3.7.0)
Requirement already satisfied: cloudpickle>=3.0 in c:\Users\snehal\AppData\Local\Programs\Python\Python314\Lib\site-packages (from joblib>=1.4.0->scikit-learn) (3.1.2)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv("C:\ITvedant\Machine Learning\customers.csv")

<>:1: SyntaxWarning: "\I" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\I"? A raw string is also an option.
<>:1: SyntaxWarning: "\I" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\I"? A raw string is also an option.
C:\Users\snehal\AppData\Local\Temp\ipykernel_4344\2517419941.py:1: SyntaxWarning: "\I" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\I"? A raw string is also an option.
  df=pd.read_csv("C:\ITvedant\Machine Learning\customers.csv")

In [4]:
df.head() # Display the first 5 rows of the DataFrame

,Channel,Region,Fresh,Milk,Grocery,Frozen,Detergents_Paper,Delicatessen
0,2,3,12669,9656,7561,214,2674,1338
1,2,3,7057,9810,9568,1762,3293,1776
2,2,3,6353,8808,7684,2405,3516,7844
3,1,3,13265,1196,4221,6404,507,1788
4,2,3,22615,5410,7198,3915,1777,5185

In [5]:
df.tail() # Display the last 5 rows of the DataFrame

,Channel,Region,Fresh,Milk,Grocery,Frozen,Detergents_Paper,Delicatessen
435,1,3,29703,12051,16027,13135,182,2204
436,1,3,39228,1431,764,4510,93,2346
437,2,3,14531,15488,30243,437,14841,1867
438,1,3,10290,1981,2232,1038,168,2125
439,1,3,2787,1698,2510,65,477,52

In [6]:
df.shape # Display the number of rows and columns in the DataFrame

(440, 8)

In [7]:
df.columns # Display the column names of the DataFrame

Index(['Channel', 'Region', 'Fresh', 'Milk', 'Grocery', 'Frozen',
       'Detergents_Paper', 'Delicatessen'],
      dtype='str')

In [8]:
df.info() # Display information about the DataFrame, including data types and non-null counts

<class 'pandas.DataFrame'>
RangeIndex: 440 entries, 0 to 439
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Channel           440 non-null    int64
 1   Region            440 non-null    int64
 2   Fresh             440 non-null    int64
 3   Milk              440 non-null    int64
 4   Grocery           440 non-null    int64
 5   Frozen            440 non-null    int64
 6   Detergents_Paper  440 non-null    int64
 7   Delicatessen      440 non-null    int64
dtypes: int64(8)
memory usage: 27.6 KB

In [9]:
df.describe() # Display summary statistics for numerical columns in the DataFrame

,Channel,Region,Fresh,Milk,Grocery,Frozen,Detergents_Paper,Delicatessen
count,440.000000,440.000000,440.000000,440.000000,440.000000,440.000000,440.000000,440.000000
mean,1.322727,2.543182,12000.297727,5796.265909,7951.277273,3071.931818,2881.493182,1524.870455
std,0.468052,0.774272,12647.328865,7380.377175,9503.162829,4854.673333,4767.854448,2820.105937
min,1.000000,1.000000,3.000000,55.000000,3.000000,25.000000,3.000000,3.000000
25%,1.000000,2.000000,3127.750000,1533.000000,2153.000000,742.250000,256.750000,408.250000
50%,1.000000,3.000000,8504.000000,3627.000000,4755.500000,1526.000000,816.500000,965.500000
75%,2.000000,3.000000,16933.750000,7190.250000,10655.750000,3554.250000,3922.000000,1820.250000
max,2.000000,3.000000,112151.000000,73498.000000,92780.000000,60869.000000,40827.000000,47943.000000

In [10]:
df.isnull().sum() # Check for missing values in each column of the DataFrame

Channel             0
Region              0
Fresh               0
Milk                0
Grocery             0
Frozen              0
Detergents_Paper    0
Delicatessen        0
dtype: int64

In [11]:
df.duplicated().sum() # Check for duplicate rows in the DataFrame

np.int64(0)

In [12]:
df.dtypes # Display the data types of each column in the DataFrame

Channel             int64
Region              int64
Fresh               int64
Milk                int64
Grocery             int64
Frozen              int64
Detergents_Paper    int64
Delicatessen        int64
dtype: object

In [13]:
df_num = df.select_dtypes(include= 'number') # Select only the numerical columns from the DataFrame
df_cat = df.select_dtypes(include=['object', 'category']) # Select only the categorical columns from the DataFrame

In [14]:
df_num.columns # Display the column names of the numerical DataFrame

Index(['Channel', 'Region', 'Fresh', 'Milk', 'Grocery', 'Frozen',
       'Detergents_Paper', 'Delicatessen'],
      dtype='str')

In [15]:
df_num.skew() # Calculate the skewness of each numerical column in the DataFrame

Channel              0.760951
Region              -1.283627
Fresh                2.561323
Milk                 4.053755
Grocery              3.587429
Frozen               5.907986
Detergents_Paper     3.631851
Delicatessen        11.151586
dtype: float64

In [16]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [17]:
df = pd.read_csv("C:\ITvedant\Machine Learning\mediclaim.csv")

<>:1: SyntaxWarning: "\I" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\I"? A raw string is also an option.
<>:1: SyntaxWarning: "\I" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\I"? A raw string is also an option.
C:\Users\snehal\AppData\Local\Temp\ipykernel_4344\3867773257.py:1: SyntaxWarning: "\I" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\I"? A raw string is also an option.
  df = pd.read_csv("C:\ITvedant\Machine Learning\mediclaim.csv")

In [18]:
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [19]:
print(df.shape)
print(df.info())
print(df.describe())
print(df.isnull().sum())

(1338, 7)
<class 'pandas.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   str
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   str
 5   region    1338 non-null   str
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), str(3)
memory usage: 73.3 KB
None
               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010
age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [20]:
print(df.select_dtypes(include='object').columns)

print(df.select_dtypes(include=np.number).columns)

Index(['sex', 'smoker', 'region'], dtype='str')
Index(['age', 'bmi', 'children', 'charges'], dtype='str')

C:\Users\snehal\AppData\Local\Temp\ipykernel_4344\999588473.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  print(df.select_dtypes(include='object').columns)

In [21]:
df = pd.get_dummies(df, drop_first=True)

df.head()

,age,bmi,children,charges,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest
0,19,27.900,0,16884.92400,False,True,False,False,True
1,18,33.770,1,1725.55230,True,False,False,True,False
2,28,33.000,3,4449.46200,True,False,False,True,False
3,33,22.705,0,21984.47061,True,False,True,False,False
4,32,28.880,0,3866.85520,True,False,True,False,False

In [22]:
print(df.columns)

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes',
       'region_northwest', 'region_southeast', 'region_southwest'],
      dtype='str')

In [23]:
print(df.isnull().sum())

age                 0
bmi                 0
children            0
charges             0
sex_male            0
smoker_yes          0
region_northwest    0
region_southeast    0
region_southwest    0
dtype: int64

In [24]:
x = df.drop("charges", axis=1)
y = df["charges"]

print("X shape:", x.shape)
print("y shape:", y.shape)

X shape: (1338, 8)
y shape: (1338,)

In [25]:
X_train, X_test, y_train, y_test = train_test_split(
    x, y, 
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)

(1070, 8)
(268, 8)

In [26]:
scaler =  StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [27]:
lr = LinearRegression()

lr.fit(X_train_scaled, y_train)

y_pred_lr = lr.predict(X_test_scaled)

In [28]:
mae_lr = mean_absolute_error(y_test, y_pred_lr)
mse_lr = mean_squared_error(y_test, y_pred_lr)
rmse_lr = np.sqrt(mse_lr)
r2_lr = r2_score(y_test, y_pred_lr)

print("Linear Regression Results")
print("-------------------------")
print("MAE  :", mae_lr)
print("MSE  :", mse_lr)
print("RMSE :", rmse_lr)
print("R2   :", r2_lr)

Linear Regression Results
-------------------------
MAE  : 4181.194473753654
MSE  : 33596915.85136149
RMSE : 5796.284659276275
R2   : 0.7835929767120722

In [30]:
ridge = Ridge(alpha=1.0)

ridge.fit(X_train_scaled, y_train)

y_pred_ridge = ridge.predict(X_test_scaled)

In [31]:
mae_ridge = mean_absolute_error(y_test, y_pred_ridge)
mse_ridge = mean_squared_error(y_test, y_pred_ridge)
rmse_ridge = np.sqrt(mse_ridge)
r2_ridge = r2_score(y_test, y_pred_ridge)

print("Ridge Regression Results")
print("------------------------")
print("MAE  :", mae_ridge)
print("MSE  :", mse_ridge)
print("RMSE :", rmse_ridge)
print("R2   :", r2_ridge)

Ridge Regression Results
------------------------
MAE  : 4182.796596583273
MSE  : 33604973.53996333
RMSE : 5796.979691180859
R2   : 0.7835410749121384

In [32]:
lasso = Lasso(alpha=1.0, max_iter=10000)

lasso.fit(X_train_scaled, y_train)

y_pred_lasso = lasso.predict(X_test_scaled)

In [ ]:
mar_lasso = mean_absolute_error(y_test, y_pred_lasso)
mse_lasso = mean_squared_error(y_test, y_pred_lasso)
rmse_lasso = np.sqrt(mse_lasso)
r2_lasso = r2_score(y_test, y_pred_lasso)

print("Lasso Regression Results")
print("------------------------")
print("MAE  :", mar_lasso)
print("MSE  :", mse_lasso)
print("RMSE :", rmse_lasso)
print("R2   :", r2_lasso)

Lasso Regression Results
------------------------
MAE  : 4181.51023183887
MSE  : 33601146.0166981
RMSE : 5796.6495509646
R2   : 0.7835657290476568

In [35]:
results = pd.DataFrame({
    "Model": ["Linear Regression", "Ridge Regression", "Lasso Regression"],
    "MAE": [mae_lr, mae_ridge, mar_lasso],
    "MSE": [mse_lr, mse_ridge, mse_lasso],
    "RMSE": [rmse_lr, rmse_ridge, rmse_lasso],
    "R2 Score": [r2_lr, r2_ridge, r2_lasso]
})

results

               Model          MAE           MSE         RMSE  R2 Score
0  Linear Regression  4181.194474  3.359692e+07  5796.284659  0.783593
1   Ridge Regression  4182.796597  3.360497e+07  5796.979691  0.783541
2   Lasso Regression  4181.510232  3.360115e+07  5796.649551  0.783566

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder

In [2]:
df = pd.read_csv("C:\ITvedant\Machine Learning\customers.csv")

<>:1: SyntaxWarning: "\I" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\I"? A raw string is also an option.
<>:1: SyntaxWarning: "\I" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\I"? A raw string is also an option.
C:\Users\snehal\AppData\Local\Temp\ipykernel_13968\4088219537.py:1: SyntaxWarning: "\I" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\I"? A raw string is also an option.
  df = pd.read_csv("C:\ITvedant\Machine Learning\customers.csv")

In [3]:
print(df.head())

   Channel  Region  Fresh  ...  Frozen  Detergents_Paper  Delicatessen
0        2       3  12669  ...     214              2674          1338
1        2       3   7057  ...    1762              3293          1776
2        2       3   6353  ...    2405              3516          7844
3        1       3  13265  ...    6404               507          1788
4        2       3  22615  ...    3915              1777          5185

[5 rows x 8 columns]

In [4]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 440 entries, 0 to 439
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Channel           440 non-null    int64
 1   Region            440 non-null    int64
 2   Fresh             440 non-null    int64
 3   Milk              440 non-null    int64
 4   Grocery           440 non-null    int64
 5   Frozen            440 non-null    int64
 6   Detergents_Paper  440 non-null    int64
 7   Delicatessen      440 non-null    int64
dtypes: int64(8)
memory usage: 27.6 KB
None

In [5]:
print(df.isnull().sum())

Channel             0
Region              0
Fresh               0
Milk                0
Grocery             0
Frozen              0
Detergents_Paper    0
Delicatessen        0
dtype: int64

In [6]:
print(df.columns)

Index(['Channel', 'Region', 'Fresh', 'Milk', 'Grocery', 'Frozen',
       'Detergents_Paper', 'Delicatessen'],
      dtype='str')

In [10]:

X = df.drop(columns=['Channel'])
y = df['Channel']

print("Features shape:", X.shape)
print("Target shape:", y.shape)

Features shape: (440, 7)
Target shape: (440,)

In [11]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

Training data: (352, 7)
Testing data: (88, 7)

In [12]:
lr_model = Pipeline([
    ('scaler', StandardScaler()),
    ('model', LogisticRegression(max_iter=1000))
])

lr_model.fit(X_train, y_train)

y_pred_lr = lr_model.predict(X_test)

lr_accuracy = accuracy_score(y_test, y_pred_lr)

print("Logistic Regression Accuracy:",
      round(lr_accuracy * 100, 2), "%")

Logistic Regression Accuracy: 89.77 %

In [13]:
dt_model = DecisionTreeClassifier(random_state=42)

dt_model.fit(X_train, y_train)

y_pred_dt = dt_model.predict(X_test)

dt_accuracy = accuracy_score(y_test, y_pred_dt)

print("Decision Tree Accuracy:",
      round(dt_accuracy * 100, 2), "%")

Decision Tree Accuracy: 89.77 %

In [14]:
knn_model = Pipeline([
    ('scaler', StandardScaler()),
    ('model', KNeighborsClassifier(n_neighbors=5))
])

knn_model.fit(X_train, y_train)

y_pred_knn = knn_model.predict(X_test)

knn_accuracy = accuracy_score(y_test, y_pred_knn)

print("KNN Accuracy:",
      round(knn_accuracy * 100, 2), "%")

KNN Accuracy: 90.91 %

In [15]:
results = pd.DataFrame({
    'Algorithm': [
        'Logistic Regression',
        'Decision Tree',
        'KNN'
    ],
    'Accuracy (%)': [
        round(lr_accuracy * 100, 2),
        round(dt_accuracy * 100, 2),
        round(knn_accuracy * 100, 2)
    ]
})

print(results)

             Algorithm  Accuracy (%)
0  Logistic Regression         89.77
1        Decision Tree         89.77
2                  KNN         90.91